git:
  kind: github
  name: github
  server: https://github.com

oauthToken: fake
hmacToken: fake

cluster:
  crds:
    create: true

tektoncontroller:
  dashboardTemplate: '#/namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}'

engines:
  jx: false
  tekton: true

webhooks:
  terminationGracePeriodSeconds: 1
