---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: f1f95c2
  secretRef:
    name: flux-system
  url: ssh://git@github.com/dippynark/cicd-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m
  path: ./config/flavours/workload
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patchesJson6902:
  - target:
      kind: Deployment
      name: nginx
    patch:
    - op: add
      path: ./config/flavours/workload
      value: 1
