---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
    control-plane: controller-manager
  name: capk-controller-manager
  namespace: capk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-kubernetes
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/port: "8443"
        prometheus.io/scheme: https
        prometheus.io/scrape: "true"
      labels:
        cluster.x-k8s.io/provider: infrastructure-kubernetes
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /manager
          image: docker.io/dippynark/cluster-api-kubernetes-controller:v0.3.5
          imagePullPolicy: IfNotPresent
          name: manager
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      terminationGracePeriodSeconds: 10
