---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
  name: capk-leader-election-rolebinding
  namespace: capk-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capk-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: capk-system
