---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
    kubeadm.controlplane.cluster.x-k8s.io/aggregate-to-manager: "true"
  name: capk-capi-kubeadm-control-plane
rules:
  - apiGroups:
      - infrastructure.dippynark.co.uk
    resources:
      - kubernetesmachines
      - kubernetesmachinetemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
