---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cluster.x-k8s.io/aggregate-to-manager: "true"
    cluster.x-k8s.io/provider: infrastructure-kubernetes
  name: capk-capi
rules:
  - apiGroups:
      - infrastructure.dippynark.co.uk
    resources:
      - kubernetesclusters
      - kubernetesmachines
      - kubernetesmachinetemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
