apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: istio-install
spec:
  serviceAccountName: istio-install
  params:
  - name: ISTIO_TARGET_VERSION
    value: "1.8.1"
  - name: NAMESPACES
    value: "bookinfo"
  pipelineRef:
    name: istio-install
