apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr
spec:
  serviceAccountName: tekton-bot
  pipelineSpec:
    params:
    - description: git url to clone
      name: REPO_URL
      type: string
    - description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
      name: PULL_PULL_REF
      type: string
    tasks:
    - name: generate
      params:
      - name: REPO_URL
        value: $(params.REPO_URL)
      - name: PULL_PULL_REF
        value: $(params.PULL_PULL_REF)
      taskSpec:
        params:
        - description: git url to clone
          name: REPO_URL
          type: string
        - description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
          name: PULL_PULL_REF
          type: string
        stepTemplate:
          name: ""
          volumeMounts:
          - mountPath: /workspace
            name: workspace
        steps:
        - name: git-clone
          image: alpine/git:v2.30.1
          command:
          - /bin/sh
          args:
          - -ce
          - |
            git clone $(inputs.params.REPO_URL) source
            cd source
            git fetch origin $(inputs.params.PULL_PULL_REF):pr
            git branch --set-upstream-to=$(inputs.params.PULL_PULL_REF) pr
            git checkout pr
          workingDir: /workspace
        - name: generate
          image: dippynark/cicd-demo:v1.0.0
          command:
          - make
          args:
          - generate
          workingDir: /workspace/source
        - name: push
          image: alpine/git:v2.30.1
          env:
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: tekton-git-identity
          command:
          - /bin/sh
          args:
          - -ce
          - |
            if [ -n "$(git status --porcelain)" ]; then
              git status
              git add --all
              git commit -m "Generated"
              git pull --rebase
              git push
            fi
          workingDir: /workspace/source
        volumes:
        - name: workspace
          emptyDir: {}
