---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
    control-plane: controller-manager
  name: capk-controller-manager-metrics-service
  namespace: capk-system
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
    control-plane: controller-manager
