---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
  name: capk-selfsigned-issuer
  namespace: capi-webhook-system
spec:
  selfSigned: {}
