---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
  name: capk-webhook-service
  namespace: capi-webhook-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
    control-plane: controller-manager
