---
# Source: lighthouse/templates/gc-jobs-cj.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: lighthouse
  name: lighthouse-gc-jobs
  labels:
    app: jenkins-x-lighthouse-gcjobs
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: lighthouse-gc-jobs
            release: lighthouse
        spec:
          containers:
            - command:
                - /home/jx/gc-jobs
              image: gcr.io/jenkinsxio/lighthouse-gc-jobs:0.0.922
              imagePullPolicy: IfNotPresent
              args:
                - "--namespace=lighthouse"
                - "--max-age=168h"
              name: lighthouse-gc-jobs
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: lighthouse-gc-jobs
  successfulJobsHistoryLimit: 3
  schedule: "0/30 * * * *"
  startingDeadlineSeconds: 4000
  suspend: false
