---
# Source: lighthouse/templates/foghorn-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lighthouse
  name: lighthouse-foghorn
  labels:
    chart: "lighthouse-0.0.939"
    app: lighthouse-foghorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-foghorn
  template:
    metadata:
      labels:
        app: lighthouse-foghorn
    spec:
      serviceAccountName: lighthouse-foghorn
      containers:
        - name: lighthouse-foghorn
          image: gcr.io/jenkinsxio/lighthouse-foghorn:0.0.939
          imagePullPolicy: IfNotPresent
          args:
            - "--namespace=lighthouse"
          env:
            - name: "GIT_KIND"
              value: "github"
            - name: "GIT_SERVER"
              value: "https://github.com"
            - name: "GIT_USER"
              value: dippynark-bot
            - name: "GIT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: lighthouse-oauth-token
                  key: oauth
            - name: "HMAC_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: "lighthouse-hmac-token"
                  key: hmac
                  optional: false
            - name: "JX_LOG_FORMAT"
              value: "json"
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: JX_DEFAULT_IMAGE
              value: ""
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
