---
# Source: lighthouse/templates/foghorn-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: lighthouse
  name: lighthouse-foghorn
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs
    verbs:
      - create
      - delete
      - list
      - update
      - get
      - watch
      - patch
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs/status
    verbs:
      - create
      - delete
      - list
      - update
      - get
      - watch
      - patch
