---
# Source: lighthouse/templates/keeper-rb.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: lighthouse
  name: lighthouse-keeper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lighthouse-keeper
subjects:
  - kind: ServiceAccount
    name: lighthouse-keeper
