---
##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
  namespace: bookinfo
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: reviews
