---
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
  namespace: bookinfo
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: ratings
