apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/cluster/clusterissuers.cert-manager.io/letsencrypt.yaml
- ./resources/cluster/clusterrolebindings/cert-manager-cainjector.yaml
- ./resources/cluster/clusterrolebindings/cert-manager-controller-certificates.yaml
- ./resources/cluster/clusterrolebindings/cert-manager-controller-challenges.yaml
- ./resources/cluster/clusterrolebindings/cert-manager-controller-clusterissuers.yaml
- ./resources/cluster/clusterrolebindings/cert-manager-controller-ingress-shim.yaml
- ./resources/cluster/clusterrolebindings/cert-manager-controller-issuers.yaml
- ./resources/cluster/clusterrolebindings/cert-manager-controller-orders.yaml
- ./resources/cluster/clusterroles/cert-manager-cainjector.yaml
- ./resources/cluster/clusterroles/cert-manager-controller-certificates.yaml
- ./resources/cluster/clusterroles/cert-manager-controller-challenges.yaml
- ./resources/cluster/clusterroles/cert-manager-controller-clusterissuers.yaml
- ./resources/cluster/clusterroles/cert-manager-controller-ingress-shim.yaml
- ./resources/cluster/clusterroles/cert-manager-controller-issuers.yaml
- ./resources/cluster/clusterroles/cert-manager-controller-orders.yaml
- ./resources/cluster/clusterroles/cert-manager-edit.yaml
- ./resources/cluster/clusterroles/cert-manager-view.yaml
- ./resources/cluster/customresourcedefinitions/certificaterequests.cert-manager.io.yaml
- ./resources/cluster/customresourcedefinitions/certificates.cert-manager.io.yaml
- ./resources/cluster/customresourcedefinitions/challenges.acme.cert-manager.io.yaml
- ./resources/cluster/customresourcedefinitions/clusterissuers.cert-manager.io.yaml
- ./resources/cluster/customresourcedefinitions/issuers.cert-manager.io.yaml
- ./resources/cluster/customresourcedefinitions/orders.acme.cert-manager.io.yaml
- ./resources/cluster/mutatingwebhookconfigurations/cert-manager-webhook.yaml
- ./resources/cluster/namespaces/cert-manager.yaml
- ./resources/cluster/validatingwebhookconfigurations/cert-manager-webhook.yaml
- ./resources/namespaces/cert-manager/deployment-cert-manager-cainjector.yaml
- ./resources/namespaces/cert-manager/deployment-cert-manager-webhook.yaml
- ./resources/namespaces/cert-manager/deployment-cert-manager.yaml
- ./resources/namespaces/cert-manager/role-cert-manager-webhook:dynamic-serving.yaml
- ./resources/namespaces/cert-manager/rolebinding-cert-manager-webhook:dynamic-serving.yaml
- ./resources/namespaces/cert-manager/service-cert-manager-webhook.yaml
- ./resources/namespaces/cert-manager/service-cert-manager.yaml
- ./resources/namespaces/cert-manager/serviceaccount-cert-manager-cainjector.yaml
- ./resources/namespaces/cert-manager/serviceaccount-cert-manager-webhook.yaml
- ./resources/namespaces/cert-manager/serviceaccount-cert-manager.yaml
- ./resources/namespaces/kube-system/role-cert-manager-cainjector:leaderelection.yaml
- ./resources/namespaces/kube-system/role-cert-manager:leaderelection.yaml
- ./resources/namespaces/kube-system/rolebinding-cert-manager-cainjector:leaderelection.yaml
- ./resources/namespaces/kube-system/rolebinding-cert-manager:leaderelection.yaml
