---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
  name: capk-serving-cert
  namespace: capi-webhook-system
spec:
  commonName: capk-webhook-service.capi-webhook-system.svc
  dnsNames:
    - capk-webhook-service.capi-webhook-system.svc
    - capk-webhook-service.capi-webhook-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capk-selfsigned-issuer
  secretName: capk-webhook-service-cert
