---
# Source: flux/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: flux
  name: flux
  namespace: flux
  labels:
    app: flux
    chart: flux-1.6.2
    release: flux
    heritage: Helm
