apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lighthouse
spec:
  interval: 1m
  chart:
    spec:
      chart: lighthouse
      version: 0.0.939
      sourceRef:
        kind: HelmRepository
        name: lighthouse
        namespace: lighthouse
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    git:
      kind: github
      name: github
      server: https://github.com

    cluster:
      crds:
        create: true

    tektoncontroller:
      dashboardTemplate: '#/namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}'

    engines:
      jx: false
      tekton: true

    webhooks:
      terminationGracePeriodSeconds: 1

    configMaps:
      create: true
  valuesFrom:
  - kind: Secret
    name: lighthouse-helm-release
    valuesKey: values.yaml
