---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
    control-plane: controller-manager
  name: capi-controller-manager-metrics-service
  namespace: capi-system
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    cluster.x-k8s.io/provider: cluster-api
    control-plane: controller-manager
