---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capi-webhook-system/capk-serving-cert
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
  name: capk-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: capk-webhook-service
        namespace: capi-webhook-system
        path: /mutate-infrastructure-dippynark-co-uk-v1alpha2-kubernetesmachine
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mkubernetesmachine.kb.io
    rules:
      - apiGroups:
          - infrastructure.dippynark.co.uk
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - kubernetesmachines
    sideEffects: None
