apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/cluster/clusterrolebindings/capk-manager-rolebinding.yaml
- ./resources/cluster/clusterrolebindings/capk-proxy-rolebinding.yaml
- ./resources/cluster/clusterroles/capk-capi-kubeadm-control-plane.yaml
- ./resources/cluster/clusterroles/capk-capi.yaml
- ./resources/cluster/clusterroles/capk-manager-role.yaml
- ./resources/cluster/clusterroles/capk-proxy-role.yaml
- ./resources/cluster/customresourcedefinitions/kubernetesclusters.infrastructure.dippynark.co.uk.yaml
- ./resources/cluster/customresourcedefinitions/kubernetesmachines.infrastructure.dippynark.co.uk.yaml
- ./resources/cluster/customresourcedefinitions/kubernetesmachinetemplates.infrastructure.dippynark.co.uk.yaml
- ./resources/cluster/mutatingwebhookconfigurations/capk-mutating-webhook-configuration.yaml
- ./resources/cluster/namespaces/capk-system.yaml
- ./resources/namespaces/capi-webhook-system/certificate.cert-manager.io-capk-serving-cert.yaml
- ./resources/namespaces/capi-webhook-system/deployment-capk-controller-manager.yaml
- ./resources/namespaces/capi-webhook-system/issuer.cert-manager.io-capk-selfsigned-issuer.yaml
- ./resources/namespaces/capi-webhook-system/service-capk-webhook-service.yaml
- ./resources/namespaces/capk-system/deployment-capk-controller-manager.yaml
- ./resources/namespaces/capk-system/role-capk-leader-election-role.yaml
- ./resources/namespaces/capk-system/rolebinding-capk-leader-election-rolebinding.yaml
- ./resources/namespaces/capk-system/service-capk-controller-manager-metrics-service.yaml
